include:
  - ./compose/arr-stack/docker-compose.yml
  - ./compose/duplicati/docker-compose.yml
  - ./compose/nginx-proxy-manager/docker-compose.yml
  - ./compose/ntfy.sh/docker-compose.yml
  - ./compose/plex/docker-compose.yml
  - ./compose/tautulli/docker-compose.yml
  - ./compose/torrenting/docker-compose.yml
  - ./compose/homepage/docker-compose.yml
  - ./compose/autoheal/docker-compose.yml

networks:
  proxy_manager:
    name: proxy_manager
    external: true
