services:
  pyload:
    image: linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./compose/pyload/config:/config
      - ${DOWNLOADS_DIR}/pyload:/downloads
    restart: unless-stopped
    networks:
      - proxy_manager

networks:
  proxy_manager:
    external: true
