services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./compose/torrenting/prowlarr-config:/config
    restart: unless-stopped
    networks:
      - proxy_manager

  rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./compose/torrenting/rdtclient-config:/data/db
      - ${DOWNLOADS_DIR}/rdtclient:/data/downloads/rdtclient
    restart: unless-stopped
    networks:
      - proxy_manager

networks:
  proxy_manager:
    external: true
